services:
  canis-rep-1:
    build: .
    ports:
      - 5012:5012
    command: python3 src/main.py slave --id=1 --folder="local"
    networks:
      - my-network
    volumes:
      - canis-1:/app

  canis-rep-2:
    build: .
    ports:
      - 5013:5012
    command: python3 src/main.py slave --id=2 --folder="local"
    networks:
      - my-network
    volumes:
      - canis-2:/app

  canis-rep-3:
    build: .
    ports:
      - 5014:5012
    command: python3 src/main.py slave --id=3 --folder="local"
    networks:
      - my-network
    volumes:
      - canis-3:/app

  canis-rep-4:
    build: .
    ports:
      - 5015:5012
      - 50051:50051
    command: python3 src/main.py master --server_url="localhost:50051" --id=4 --folder="local"
    networks:
      - my-network
    volumes:
      - canis-4:/app

volumes:
  canis-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .
  canis-2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .
  canis-3:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .
  canis-4:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .

networks:
  my-network:
    driver: bridge