services:
  canis-rep-1:
    build: .
    ports:
      - 5012:5012
      - 5022:5022
      - 5032:5032
    command: python3 src/main.py --id=1 --folder="local" --role="leader"
    volumes:
      - canis-1:/app

  canis-rep-2:
    build: .
    ports:
      - 5013:5012
      - 5023:5022
      - 5033:5032
    command: python3 src/main.py --id=2 --folder="local"
    volumes:
      - canis-2:/app

  canis-rep-3:
    build: .
    ports:
      - 5014:5012
      - 5024:5022
      - 5034:5032
    command: python3 src/main.py --id=3 --folder="local"
    volumes:
      - canis-3:/app

  canis-rep-4:
    build: .
    ports:
      - 5015:5012
      - 5025:5022
      - 5035:5032
    command: python3 src/main.py --id=4 --folder="local"
    volumes:
      - canis-4:/app

volumes:
  canis-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .
  canis-2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .
  canis-3:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .
  canis-4:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .
